import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

const geist = localFont({
  src: [
    {
      path: '../../public/fonts/geist/Geist-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/geist/Geist-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-geist',  // 声明一个 CSS 变量
})

const geistMono = localFont({
  src: [
    {
      path: '../../public/fonts/geist/GeistMono-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/geist/GeistMono-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-geist-mono',  // 声明另一个 CSS 变量
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geist.variable} ${geistMono.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
