import type { Metadata } from "next";
import "./(style)/tailwind.css";
import "./(style)/base.css";
import "./(style)/components.css";
import "./(style)/utilities.css";
import { geist, geistMono } from "./(style)/fonts";
import { AppToaster } from "@/components/ui/toaster";
import { TranslateSwitcher } from "@/app/(translate)/Translate";
import { I18nProvider } from "@/app/(translate)/I18nProvider";
import { StoreProvider } from "@/store/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="auto">
      <body className={`${geist.variable} ${geistMono.variable} antialiased `}>
        <StoreProvider>
          <I18nProvider>
            {children}
            <TranslateSwitcher />
            <AppToaster />
          </I18nProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
